# build angular app using node.js, then deploy to azure static website
on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  APP_ARTIFACT_LOCATION: "dist" # location of client code build output
  AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }} # secret containing deployment token for your static web app
  NODE_VERSION: '16.x'                # set this to the node version to use

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build, and test
      run: |
        npm install -g @angular/cli
        npm install 
        ng build --prod

    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v2
      with:
        name: angular-app
        path: .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v2
      with:
        name: angular-app

    - name: 'Deploy to Azure Static Website'
      id: deploy-to-static-web 
      uses: TravisSpomer/deploy-to-azure-storage@v1.4.0
      with:
        source-path: dist
        sas-url: ${{ secrets.DEPLOY_SAS_URL }}
